spring:
  application:
    name: kitchen_log_api
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kitchen_log
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/kitchen_log
    user: postgres
    password: postgres