package com.example.kitchen_log_api.infrastructure.recipe.repository

import com.example.kitchen_log_api.infrastructure.recipe.entity.RecipeStepEntity
import org.springframework.data.repository.kotlin.CoroutineCrudRepository

interface RecipeStepCrudRepository: CoroutineCrudRepository<RecipeStepEntity, Long>