package com.example.kitchen_log_api.infrastructure.recipe.repository

import com.example.kitchen_log_api.infrastructure.recipe.entity.RecipeIngredientEntity
import org.springframework.data.repository.kotlin.CoroutineCrudRepository

interface RecipeIngredientCrudRepository: CoroutineCrudRepository<RecipeIngredientEntity, Long>